const dict = {
	river2pro: {
		mppt: {
			acStandbyMins: { entity: 'level' },
			beepState: { entity: 'switch' },
			carOutAmp: { entity: 'number' },
			carOutVol: { entity: 'number' },
			carOutWatts: { entity: 'number' },
			carStandbyMin: { entity: 'level' },
			carState: { entity: 'switch' },
			carTemp: { entity: 'number' },
			cfgAcEnabled: { entity: 'switch' },
			cfgAcOutFreq: { entity: 'diagnostic' },
			cfgAcOutVol: { entity: 'string' },
			cfgAcXboost: { entity: 'switch' },
			cfgChgType: { entity: 'diagnostic' },
			cfgChgWatts: { entity: 'level' },
			chgPauseFlag: { entity: 'switch' },
			chgState: { entity: 'diagnostic' },
			chgType: { entity: 'diagnostic' },
			dc24vState: { entity: 'diagnostic' },
			dc24vTemp: { entity: 'number' },
			dcChgCurrent: { entity: 'level' },
			dcdc12vAmp: { entity: 'number' },
			dcdc12vVol: { entity: 'number' },
			dcdc12vWatts: { entity: 'number' },
			dischargeType: { entity: 'diagnostic' },
			faultCode: { entity: 'string' },
			inAmp: { entity: 'number' },
			inVol: { entity: 'number' },
			inWatts: { entity: 'number' },
			mpptTemp: { entity: 'number' },
			outAmp: { entity: 'number' },
			outVol: { entity: 'number' },
			outWatts: { entity: 'number' },
			powStandbyMin: { entity: 'number' },
			res: { entity: 'icon' },
			scrStandbyMin: { entity: 'number' },
			swVer: { entity: 'string' },
			x60ChgType: { entity: 'diagnostic' }
		},
		ems: {
			bmsIsConnt: { entity: 'string' },
			bmsModel: { entity: 'string' },
			bmsWarState: { entity: 'diagnostic' },
			chgAmp: { entity: 'number' },
			chgCmd: { entity: 'diagnostic' },
			chgRemainTime: { entity: 'number' },
			chgState: { entity: 'diagnostic' },
			chgVol: { entity: 'number' },
			dsgCmd: { entity: 'diagnostic' },
			dsgRemainTime: { entity: 'number' },
			emsIsNormalFlag: { entity: 'diagnostic' },
			f32LcdShowSoc: { entity: 'number' },
			fanLevel: { entity: 'string' },
			lcdShowSoc: { entity: 'number' },
			maxAvailNum: { entity: 'string' },
			maxChargeSoc: { entity: 'level' },
			maxCloseOilEb: { entity: 'level' },
			minDsgSoc: { entity: 'level' },
			minOpenOilEb: { entity: 'level' },
			openBmsIdx: { entity: 'string' },
			openUpsFlag: { entity: 'string' },
			paraVolMax: { entity: 'number' },
			paraVolMin: { entity: 'number' }
		},
		pd: {
			acAutoOutConfig: { entity: 'switch' }, //
			acAutoOutPause: { entity: 'number' }, //
			beepMode: { entity: 'diagnostic' },
			bpPowerSoc: { entity: 'level' }, //
			brightLevel: { entity: 'string' },
			carState: { entity: 'diagnostic' }, //
			carTemp: { entity: 'number' },
			carUsedTime: { entity: 'number' },
			carWatts: { entity: 'number' },
			chgDsgState: { entity: 'diagnostic' },
			chgPowerAC: { entity: 'number' },
			chgPowerDC: { entity: 'number' },
			chgSunPower: { entity: 'number' },
			dcInUsedTime: { entity: 'number' },
			dcOutState: { entity: 'switch' },
			dsgPowerAC: { entity: 'number' },
			dsgPowerDC: { entity: 'number' },
			errCode: { entity: 'string' },
			ext3p8Port: { entity: 'diagnostic' },
			ext4p8Port: { entity: 'diagnostic' },
			extRj45Port: { entity: 'diagnostic' },
			hysteresisAdd: { entity: 'string' }, //
			icoBytes: { entity: 'icon' },
			invUsedTime: { entity: 'number' },
			lcdOffSec: { entity: 'level' },
			minAcoutSoc: { entity: 'number' },
			model: { entity: 'string' },
			mpptUsedTime: { entity: 'number' },
			qcUsb1Watts: { entity: 'number' },
			qcUsb2Watts: { entity: 'number' },
			relaySwitchCnt: { entity: 'string' },
			remainTime: { entity: 'number' },
			soc: { entity: 'number' },
			standbyMin: { entity: 'level' },
			sysVer: { entity: 'string' },
			typec1Temp: { entity: 'number' },
			typec1Watts: { entity: 'number' },
			typec2Temp: { entity: 'number' },
			typec2Watts: { entity: 'number' },
			typecChaWatts: { entity: 'number' },
			typecUsedTime: { entity: 'number' },
			usb1Watts: { entity: 'number' },
			usb2Watts: { entity: 'number' },
			usbqcUsedTime: { entity: 'number' },
			usbUsedTime: { entity: 'number' },
			watchIsConfig: { entity: 'diagnostic' },
			wattsInSum: { entity: 'number' },
			wattsOutSum: { entity: 'number' },
			wifiAutoRcvy: { entity: 'diagnostic' },
			wifiRssi: { entity: 'string' },
			wifiVer: { entity: 'string' },
			wireWatts: { entity: 'string' }
		},
		inv: {
			acDipSwitch: { entity: 'diagnostic' },
			acInAmp: { entity: 'number' },
			acInFreq: { entity: 'number' },
			acInVol: { entity: 'number' },
			cfgAcEnabled: { entity: 'switch' },
			cfgAcOutFreq: { entity: 'diagnostic' },
			cfgAcOutVol: { entity: 'string' },
			cfgAcWorkMode: { entity: 'switch' },
			cfgAcXboost: { entity: 'switch' },
			chargerType: { entity: 'diagnostic' },
			chgPauseFlag: { entity: 'switch' },
			dcInAmp: { entity: 'number' },
			dcInTemp: { entity: 'number' },
			dcInVol: { entity: 'number' },
			dischargeType: { entity: 'diagnostic' },
			errCode: { entity: 'string' },
			fanState: { entity: 'diagnostic' },
			FastChgWatts: { entity: 'number' },
			inputWatts: { entity: 'number' },
			invOutAmp: { entity: 'number' },
			invOutFreq: { entity: 'number' },
			invOutVol: { entity: 'number' },
			invType: { entity: 'string' },
			outputWatts: { entity: 'number' },
			outTemp: { entity: 'number' },
			reserved: { entity: 'icon' },
			SlowChgWatts: { entity: 'level' },
			standbyMins: { entity: 'number' },
			sysVer: { entity: 'string' }
		},
		bmsMaster: {
			amp: { entity: 'number' },
			bmsFault: { entity: 'string' },
			bqSysStatReg: { entity: 'string' },
			cellId: { entity: 'diagnostic' },
			cycles: { entity: 'number' },
			designCap: { entity: 'number' },
			errCode: { entity: 'diagnostic' },
			f32ShowSoc: { entity: 'number' },
			fullCap: { entity: 'number' },
			inputWatts: { entity: 'number' },
			maxCellTemp: { entity: 'number' },
			maxCellVol: { entity: 'number' },
			maxMosTemp: { entity: 'number' },
			minCellTemp: { entity: 'number' },
			minCellVol: { entity: 'number' },
			minMosTemp: { entity: 'number' },
			num: { entity: 'string' },
			openBmsIdx: { entity: 'string' },
			outputWatts: { entity: 'number' },
			remainCap: { entity: 'number' },
			remainTime: { entity: 'number' },
			soc: { entity: 'number' },
			soh: { entity: 'string' },
			sysVer: { entity: 'string' },
			tagChgAmp: { entity: 'number' },
			temp: { entity: 'number' },
			type: { entity: 'diagnostic' },
			vol: { entity: 'number' }
		}
	}
};
