const dict = {
	rivermax: {
		inv: {
			cfgFanMode: { entity: 'diagnostic' },
			dcInVol: { entity: 'number' },
			cfgAcOutVoltage: { entity: 'string' },
			cfgAcChgModeFlg: { entity: 'diagnostic' },
			cfgStandbyMin: { entity: 'level' },
			dcInAmp: { entity: 'number' },
			cfgAcOutFreq: { entity: 'diagnostic' },
			errCode: { entity: 'string' },
			outputWatts: { entity: 'number' },
			invOutFreq: { entity: 'number' },
			chargerType: { entity: 'diagnostic' },
			fanState: { entity: 'diagnostic' },
			undefined: { entity: 'string' },
			inTemp: { entity: 'number' },
			cfgAcEnabled: { entity: 'switch' },
			cfgAcXboost: { entity: 'switch' },
			outTemp: { entity: 'number' },
			invType: { entity: 'string' },
			invOutVol: { entity: 'number' },
			invInAmp: { entity: 'number' },
			inputWatts: { entity: 'number' },
			invInFreq: { entity: 'number' },
			invOutAmp: { entity: 'number' },
			invInVol: { entity: 'number' },
			sysVer: { entity: 'string' }
		},
		bmsMaster: {
			maxCellTemp: { entity: 'number' },
			bmsFault: { entity: 'string' },
			undefined: { entity: 'string' },
			sysVer: { entity: 'string' },
			temp: { entity: 'number' },
			cycles: { entity: 'number' },
			remainCap: { entity: 'number' },
			vol: { entity: 'number' },
			errCode: { entity: 'diagnostic' },
			minCellVol: { entity: 'number' },
			soc: { entity: 'number' },
			bqSysStatReg: { entity: 'string' },
			amp: { entity: 'number' },
			minCellTemp: { entity: 'number' },
			minMosTemp: { entity: 'number' },
			maxCellVol: { entity: 'number' },
			fullCap: { entity: 'number' },
			maxMosTemp: { entity: 'number' },
			// nur bei slave
			ambientLightColor: { entity: 'icon' },
			ambientLightBrightness: { entity: 'icon' },
			ambientLightAnimate: { entity: 'icon' },
			ambientLightEnabled: { entity: 'icon' }
		},
		pd: {
			wattsInSum: { entity: 'number' },
			dcInUsedTime: { entity: 'number' },
			chgPowerDC: { entity: 'number' },
			dsgPowerDC: { entity: 'number' },
			model: { entity: 'string' },
			ledState: { entity: 'diagnostic' },
			beepState: { entity: 'switch' },
			remainTime: { entity: 'number' },
			usb3Watts: { entity: 'number' },
			typecUsedTime: { entity: 'number' },
			typecWatts: { entity: 'number' },
			usbqcUsedTime: { entity: 'number' },
			chgSunPower: { entity: 'number' },
			wattsOutSum: { entity: 'number' },
			carSwitch: { entity: 'diagnostic' },
			carTemp: { entity: 'number' },
			usbUsedTime: { entity: 'number' },
			mpptUsedTime: { entity: 'number' },
			ledWatts: { entity: 'number' },
			usb1Watts: { entity: 'number' },
			standByMode: { entity: 'level' },
			undefined: { entity: 'string' },
			dsgPowerAC: { entity: 'number' },
			chgPowerAC: { entity: 'number' },
			errCode: { entity: 'diagnostic' },
			bmsSlave: { entity: 'string' },
			sysVer: { entity: 'string' },
			carWatts: { entity: 'number' },
			carUsedTime: { entity: 'number' },
			usb2Watts: { entity: 'number' },
			soc: { entity: 'number' },
			typecTemp: { entity: 'number' },
			invUsedTime: { entity: 'number' }
		}
	}
};
