'use strict';

const models = {
    smartmeter: {
        identifiers: 'BK21Zxxxxx',
        type: 1, //unbekannt
        manufacturer: 'Ecoflow',
        model: 'EF Smartmeter',
        name: 'EF Smartmeter',
    },
    efxshellypro3em: {
        identifiers: 'SM3Axxxxx',
        type: 1, //unbekannt
        manufacturer: 'Shelly',
        model: 'EF x Shelly Pro3EM',
        name: 'EF Flow x Shelly Pro3EM',
    },
    shelly3em: {
        identifiers: '012345xxxx',
        type: 99, //eventuell auch 75
        manufacturer: 'Shelly',
        model: 'Shelly 3 EM',
        name: 'Shelly 3 EM',
    },
    pstream600: {
        identifiers: 'HW51Zxxxx',
        type: 67, //eventuell auch 75
        manufacturer: 'Ecoflow',
        model: 'Power Stream 600',
        name: 'Power Stream',
    },
    pstream800: {
        identifiers: 'HW51Zxxxx',
        type: 75,
        manufacturer: 'Ecoflow',
        model: 'Power Stream 800',
        name: 'Power Stream',
    },
    plug: {
        identifiers: 'HW52Zxxxx',
        manufacturer: 'Ecoflow',
        model: 'Ecoflow Smart Plug',
        name: 'Ecoflow Smart Plug',
    },
    plugefshelly: {
        identifiers: 'HW52Zxxxx',
        manufacturer: 'Shelly',
        model: 'Eco Flow x Shelly Smart Plug',
        name: 'Eco Flow x Shelly Smart Plug',
    },
    deltamini: {
        identifiers: 'DAEBZ5xxx',
        manufacturer: 'Ecoflow',
        model: 'Delta Mini, 882Wh',
        name: 'Delta Mini',
        type: 15,
        spec: {
            capacity: '882Wh, 50,4V',
            acInputPower: '900W',
            solarInput: '11-75V, 10A, 300W',
            carInput: '12/24V, 8A',
            acOutput: '1400W',
            acOutputPeak: '2100W',
            xboost: '2200W',
            carOutput: '12,6V, 10A, 126W',
        },
    },
    delta: {
        identifiers: 'DAEBZ5xxx',
        manufacturer: 'Ecoflow',
        model: 'Delta 1260Wh',
        name: 'Delta',
        spec: {
            capacity: '1260Wh, 50,4V',
            acInputPower: '1200W',
            solarInput: '10-65V, 10A, 400W',
            carInput: '12/24V, 10A',
            acOutput: '1800W',
            acOutputPeak: '3300W',
            carOutput: '13,6V, 8A, 108,8W',
        },
    },
    deltamax: {
        identifiers: 'DAEBZ5xxx',
        manufacturer: 'Ecoflow',
        model: 'Delta Max 1600/2000Wh',
        name: 'Delta Max',
        type: 13,
        spec: {
            capacity: '2016Wh, 50,4V',
            acInputPower: '2000W',
            solarInput: '11-100V, 10A, 800W',
            carInput: '12/24V, 8A',
            acOutput: '2400W',
            acOutputPeak: '4600W',
            xboost: '3000W',
            carOutput: '12,6V, 10A, 126W',
        },
    },
    deltapro: {
        identifiers: 'DCExxx',
        manufacturer: 'Ecoflow',
        model: 'Delta Pro, 3600Wh',
        name: 'Delta Pro',
        spec: {
            capacity: '3600Wh, 48V',
            acInputPower: '2875W',
            solarInput: '11-150V, 15A, 1600W',
            carInput: '12/24V, 8A',
            acOutput: '3600W',
            acOutputPeak: '7200W',
            xboost: '4500W',
            carOutput: '12,6V, 10A, 126W',
            andersonOutput: '12,6V,30A, 378W',
        },
    },
    delta2: {
        identifiers: 'R331Zxxx',
        manufacturer: 'Ecoflow',
        model: 'Delta 2, 1024Wh',
        name: 'Delta 2',
        moduleType: {
            1: 'PD',
            2: 'BMS',
            3: 'INV',
            4: 'BMS_SLAVE',
            5: 'MPPT',
        },
        type: 80,
        spec: {
            capacity: '1024Wh, (51,2V)',
            acInputPower: '1200W',
            solarInput: '11-60V, 15A, 500W',
            carInput: '12/24V, 8A',
            acOutput: '1800W',
            acOutputPeak: '2700W',
            xboost: '2200W',
            carOutput: '12,6V, 10A, 126W',
        },
    },
    delta2max: {
        identifiers: 'R351Zxxxxxx',
        manufacturer: 'Ecoflow',
        model: 'Delta 2 Max, EFD350,2048Wh',
        name: 'Delta 2 Max',
        moduleType: {
            1: 'PD',
            2: 'BMS',
            3: 'INV',
            4: 'BMS_SLAVE',
            5: 'MPPT',
        },
        type: 81,
        spec: {
            capacity: '2048Wh',
            acInputPower: '2400W',
            solarInput: '11-60V, 15A, 500W',
            carInput: '12V, 8A, 96W',
            acOutput: '2400W',
            acOutputPeak: '4800W',
            xboost: '3400W',
            carOutput: '12,6V, 10A, 126W',
        },
    },
    deltaproultra: {
        identifiers: 'R331Zxxx',
        manufacturer: 'Ecoflow',
        model: 'Delta Pro Ultra, 6000Wh',
        name: 'Delta Pro Ultra',
        moduleType: {
            1: 'PD',
            2: 'BMS',
            3: 'INV',
            4: 'BMS_SLAVE',
            5: 'MPPT',
        },
        type: 89,
        spec: {
            capacity: '102.4V⎓60A, 6,144Wh',
            acInputPower:
                '(Charging only) 100-120V~15A; 200-240V~12.5A, 50/60 Hz;(Bypass) 100-120V~ 15A, 50/60 Hz (duration < 3hrs when the current exceeds 12A)',
            solarInput: '80-450V⎓15A max, 4,000W max; 30-150V⎓15A max, 1,600W max',
            acOutput:
                'Discharging only) Pure sine, 7,200W total, 120/240 V~ 60 Hz; (Bypass) 100-120V~30A max, 50/60 Hz',
            usbOutput:
                'USB-A: 5V⎓2.4A, 12W max per port, total 24W; USB-C: 5/9/12/15/20V⎓5A, 100W max per port, total 200W',
            dcInput: '12V 8A max, 48V 20A max',
            carOutput: '12.6V⎓30A, 378W max',
        },
    },
    deltapro3: {
        identifiers: 'R331Zxxx', //todo
        manufacturer: 'Ecoflow',
        model: 'Delta Pro 3, 4096Wh',
        name: 'Delta Pro 3',
        type: 89, //todo
        spec: {
            capacity: 'V⎓A, 4096Wh',
            acInputPower: '(Charging only) 200-240V~12.5A, 50/60 Hz 2900W max',
            solarInput: '30-150V⎓15A max, 1600W max; 11-60V⎓20A max, 1000W max',
            acOutput: '4000W, (6000W X-Boost), max 8000W',
            usbOutput:
                'USB-A fast charge: 5V⎓2,4A/9⎓2A/12V⎓1,5A, 2x, 18W max per port; USB-C: 5/9/12/15/20V⎓5A, 2x, 100W max per port',
            carOutput: '12.6V⎓30A, 378W max, DC5521 1x 3 A max, Anderson 1x 30A max.',
        },
    },
    delta3plus: {
        identifiers: 'MR51xxx', //todo
        manufacturer: 'Ecoflow',
        model: 'Delta 3 Plus, 1536Wh',
        name: 'Delta 3 Plus',
        type: 89, //todo
        spec: {
            capacity: 'V⎓A, 1536Wh',
            acInputPower: '(Charging only) 100-120V~15A; 200-240V~12.5A, 50/60 Hz 1500W;',
            solarInput: '11-60V⎓ A max, 2x 500W max',
            acOutput: '1800W, 3600W X-Boost',
            usbOutput:
                'USB-A: 5V⎓2.4A, 2x, 12W max per port; USB-A fast charge: 5V⎓2,4A/9⎓2A/12V⎓1,5A 2x, 18W max per port, USB-C: 5/9/12/15/20V⎓5A, 2x, 100W max per port',
            carOutput: '12.6V⎓10A, 126W max, DC5521 2 × 12,6 V, 3 A max',
        },
    },
    delta3: {
        identifiers: 'R331Zxxx', //todo
        manufacturer: 'Ecoflow',
        model: 'Delta 3, 1024Wh',
        name: 'Delta 3',
        type: 89, //todo
        spec: {
            capacity: 'V⎓ A, 1024Wh',
            acInputPower: '(Charging only) 100-120V~A; 200-240V~A, 50/60 Hz, 1500W',
            solarInput: '11-60V⎓ A max, 1x 500W max',
            acOutput: '1800W, 3600W X-Boost',
            usbOutput:
                'USB-A fast charge: 5V⎓2,4A/9⎓2A/12V⎓1,5A, 2x, 18W max per port; USB-C: 5/9/12/15/20V⎓5A, 2x, 100W max per port',
            carOutput: '12.6V⎓10A, 126W max, DC5521 2 × 12,6 V, 3 A max',
        },
    },
    river2max: {
        identifiers: 'Rxxx',
        manufacturer: 'Ecoflow',
        model: 'River 2 Max, EFR610, 512Wh  ',
        name: 'River 2 Max',
        type: 71,
        spec: {
            capacity: '512Wh, (20Ah, 25,6V)',
            acInputPower: '10A',
            usbcInput: '100W',
            solarInput: '11-50V, 13A, 220W',
            carInput: '12/24V, 8A, 100W',
            acOutput: '500W',
            acOutputPeak: '1000W',
            carOutput: '12,6V, 10A, 126W',
        },
    },
    rivermax: {
        identifiers: 'Rxxx',
        manufacturer: 'Ecoflow',
        model: 'River Max, 576Wh  ',
        name: 'River 2 Max',
        spec: {
            capacity: '576Wh, (28,8V)',
            acInputPower: '500W',
            solarInput: '10-25V, 12A, 200W',
            carInput: '12V, 8A',
            acOutput: '600W',
            acOutputPeak: '1200W',
            xboost: '1800W',
            carOutput: '13,6V, 10A, 136W',
        },
    },
    river2pro: {
        identifiers: 'R6xxx',
        manufacturer: 'Ecoflow',
        model: 'River 2 Pro, EFR620 768Wh  ',
        name: 'River 2 Pro',
        moduleType: {
            1: 'PD',
            2: 'BMS',
            3: 'INV',
            5: 'MPPT',
        },
        type: 72,
        spec: {
            capacity: '768Wh, (40Ah, 19,2V)',
            acInputPower: '8A',
            usbcInput: '100W',
            solarInput: '11-50V, 13A, 220W',
            carInput: '12/24V, 8A, 100W',
            acOutput: '800W',
            acOutputPeak: '1600W',
            carOutput: '12,6V, 10A, 126W',
        },
    },
    riverpro: {
        identifiers: 'Rxxx',
        manufacturer: 'Ecoflow',
        model: 'River Pro, 720Wh  ',
        name: 'River Pro',
        type: 12,
        spec: {
            capacity: '720Wh, (28,8V)',
            acInputPower: '660W',
            usbcInput: '100W',
            solarInput: '10-25V, 12A, 200W',
            carInput: '12V, 8A',
            acOutput: '600W',
            acOutputPeak: '1200W',
            carOutput: '13,6V, 10A, 136W',
        },
    },
    river3: {
        identifiers: 'Rxxx',
        manufacturer: 'Ecoflow',
        model: 'River 3, 245Wh  ',
        name: 'River 3',
        spec: {
            capacity: '245Wh, (6800mAh)',
            acInputPower: '3A',
            generatorInput: '100~120V, 6.5A Max, 50/60Hz, 320W; 200-240 V, 3 A max., 50/60 Hz, 300 W',
            usbaOutput: '2 ports, 5V⎓2.4A, 12W Max per port, total 24W',
            usbcOutput: '1 × 5/9/12/15 V⎓3 A max., 20 V⎓5 A max., 100 W pro Ausgang',
            solarInput: '11-50V, 13A, 220W',
            carInput: '11-30V, 8A, 100W',
            acOutput: '300W',
            acOutputPeak: '600W',
            carOutput: '12,6V, 10A, 126W',
        },
    },
    river3plus: {
        identifiers: 'Rxxx',
        manufacturer: 'Ecoflow',
        model: 'River 3 Plus, 286Wh  ',
        name: 'River 3 Plus',
        spec: {
            capacity: '286Wh, (9600mAh)',
            acInputPower: '10A',
            generatorInput: '100~120V, 6.5A Max 50/60Hz, 380W; 200-240 V, 3 A max., 50/60 Hz, 360 W',
            usbaOutput: '2 ports, 5V⎓2.4A, 12W Max per port, total 24W',
            usbcOutput: '1 × 5/9/12/15 V⎓3 A max., 20 V⎓5 A max., 100 W pro Ausgang',
            solarInput: '11-50V, 13A, 220W',
            carInput: '11-55V, 8A, 220W',
            acOutput: '600W',
            acOutputPeak: '1200W',
            carOutput: '12,6V, 10A, 126W',
            addBatt: { eb300: '286Wh', eb600: '572Wh' },
        },
    },
    river3max: {
        identifiers: 'Rxxx',
        manufacturer: 'Ecoflow',
        model: 'River 3 Max, 572Wh  ',
        name: 'River 3 Max',
        spec: {
            capacity: '572Wh',
        },
    },
    wave2: {
        identifiers: 'KT21ZCHxxxx',
        manufacturer: 'Ecoflow',
        model: 'WAVE 2 Air Conditioner',
        name: 'WAVE 2 Air EFKT210',
        type: 45,
        moduleType: {
            1: 'PD',
            2: 'POWER',
            3: 'MOTOR',
            4: 'BMS',
        },
        spec: {
            acInputPower: '820W',
            addOnBatteryPower: '700W',
            coolInputAC: '550W',
            coolInputDC: '495W',
            heatInputAC: '600W',
            heatInputDC: '540W',
            maxCoolPower: '700W',
            maxHeatPower: '700W',
            coolingCapacity: '1500Wh/5100BTU',
            heatingCapacity: '1800Wh/6100BTU',
            solarInput: '11-60V, 13A, 400W',
            carInput: '12/24V, 8A, 200W',
        },
        // Zusatzakku 1159Wh
        // oder Akku Delta Serie
        // Gerät hat selbst keinen Akku
    },
    wave3: {
        identifiers: 'AC71ZCxxxx',
        manufacturer: 'Ecoflow',
        model: 'WAVE 3 Air Conditioner',
        name: 'WAVE 3 Air',
        type: 45,
        spec: {
            acInputPower: '820W',
            addOnBatteryPower: '700W',
            coolInputAC: '550W',
            coolInputDC: '495W',
            heatInputAC: '600W',
            heatInputDC: '540W',
            maxCoolPower: '700W',
            maxHeatPower: '700W',
            coolingCapacity: '1500Wh/5100BTU',
            heatingCapacity: '1800Wh/6100BTU',
            solarInput: '11-60V, 13A, 400W',
            carInput: '12/24V, 8A, 200W',
        },
        // Zusatzakku 1159Wh
        // oder Akku Delta Serie
        // Gerät hat selbst keinen Akku
    },
    glacier: {
        identifiers: 'BX11ZCBxxxx',
        manufacturer: 'Ecoflow',
        model: 'GLACIER Cooler',
        name: 'GLACIER',
        moduleType: {
            1: 'PD',
            2: 'BMS',
            3: 'INV',
            4: 'BMS_SLAVE',
            5: 'MPPT',
        },
        type: 46,
        spec: {
            comprPower: '120W',
            acInputPower: '180W',
            batteryPackPower: '100W (USB-C)',
            solarInput: '11-60V, 13A, 240W',
            carInput: '12/24V, 8A, 96/192W',
        },
    },
    river2: {
        identifiers: 'Rxxx',
        manufacturer: 'Ecoflow',
        model: 'River 2,EFR600, 256Wh ',
        name: 'River 2',
        spec: {
            capacity: '256Wh, (20Ah, 12,8V)',
            acInputPower: '8A',
            usbcInput: '60W',
            solarInput: '11-30V, 8A, 110W',
            carInput: '12/24V, 8A, 100W',
            acOutput: '300W',
            acOutputPeak: '600W',
            carOutput: '12,6V, 8A, 100W',
        },
    },
    river: {
        identifiers: 'Rxxx',
        manufacturer: 'Ecoflow',
        model: 'River, 288Wh  ',
        name: 'River',
        spec: {
            capacity: '288Wh, (28,8V)',
            acInputPower: '250W',
            usbcInput: '100W',
            solarInput: '10-25V, 12A, 200W',
            carInput: '12V, 8A',
            acOutput: '600W',
            acOutputPeak: '1200W',
            xboost: '1800W',
            carOutput: '13,6V, 10A, 136W',
        },
    },
    rivermini: {
        identifiers: 'Rxxx',
        manufacturer: 'Ecoflow',
        model: 'River Mini, 210Wh  ',
        name: 'River Mini',
        spec: {
            capacity: '210Wh, (25,2V)',
            acInputPower: '300W',
            solarInput: '11-39V, 8A, 100W',
            carInput: '12/24V, 8A, 100W',
            acOutput: '300W',
            acOutputPeak: '600W',
            xboost: '600W',
            carOutput: '12,6V, 10A, 126W',
        },
    },
    wave: {
        identifiers: 'H2xxxx',
        manufacturer: 'Ecoflow',
        model: 'WAVE Air Conditioner',
        name: 'WAVE Air EFH200',
        moduleType: {
            1: 'PD',
            2: 'POWER',
            3: 'MOTOR',
            4: 'BMS',
        },
        spec: {
            acInputPower: '700W',
            addOnBatteryPower: '600W',
            coolInputAC: '460W',
            coolInputDC: '410W',
            maxCoolPower: '600W',
            coolingCapacity: '1200Wh',
            solarInput: '11-35V, 12A, 200W',
            carInput: '12/24V, 8A, 200W',
        },
    },
    tracker: {
        identifiers: 'HZ31xxxx',
        manufacturer: 'Ecoflow',
        model: 'Solar Tracker',
        name: 'Solar Tracker',
    },
    blade: {
        identifiers: 'H101Zxxxxx',
        manufacturer: 'Ecoflow',
        model: 'Blade',
        name: 'Blade',
        type: 42,
    },
    generator: {
        identifiers: 'DGEBZ5Rxxxxx',
        manufacturer: 'Ecoflow',
        model: 'Smart Generator',
        name: 'Smart Generator',
        spec: {
            acOutput: '1800W',
            acOutputPeak: '1900W',
            dcOutput: '42–58.8 V, max 32A',
        },
    },
    generatordf: {
        identifiers: 'Dxxxxx',
        manufacturer: 'Ecoflow',
        model: 'Smart Generator Dual Fuel',
        name: 'Dual Fuel Generator',
        spec: {
            acOutput: '1800W',
            acOutputPeak: '1900W',
            dcOutput: '42–58.8 V, max 32A',
        },
    },
    generator3k: {
        identifiers: 'G371xxxxx',
        manufacturer: 'Ecoflow',
        model: 'Smart Generator 3000 (Dual Fuel)',
        name: 'Smart Generator 3000 (Dual Fuel)',
        spec: {
            acOutput: '3000W',
            acOutputPeak: '3000W',
            dcOutput: '42–58.8 V, max 32A',
        },
    },
    generator4k: {
        identifiers: 'G351xxxxx',
        manufacturer: 'Ecoflow',
        model: 'Smart Generator 4000 (Dual Fuel)',
        name: 'Smart Generator 4000 (Dual Fuel)',
        spec: {
            acOutput: '4000W',
            acOutputPeak: '4000W',
            dcOutput: '42–58.8 V, max 32A',
        },
    },
    panel: {
        identifiers: 'SH10xxxxx',
        manufacturer: 'Ecoflow',
        model: 'Smart Home Panel',
        name: 'Smart Home Panel',
        type: 89, //?
    },
    panel2: {
        identifiers: 'SH20xxxxx',
        manufacturer: 'Ecoflow',
        model: 'Smart Home Panel 2',
        name: 'Smart Home Panel 2',
    },
    powerkit: {
        identifiers: 'M106ZABxxxx',
        manufacturer: 'Ecoflow',
        model: 'Power Kit & Power Hub',
        name: 'Power Kit & Power Hub',
    },
    powerkitbp2000: {
        identifiers: 'M106ZABxxxx',
        manufacturer: 'Ecoflow',
        model: 'Power Kit & Power Hub 2kWh',
        name: 'Power Kit & Power Hub',
    },
    powerkitbp5000: {
        identifiers: 'M106ZABxxxx',
        manufacturer: 'Ecoflow',
        model: 'Power Kit & Power Hub 5kWh',
        name: 'Power Kit & Power Hub',
    },
    powerocean: {
        identifiers: 'HJ31xxxx',
        manufacturer: 'Ecoflow',
        model: 'Power OCEAN DC',
        name: 'Power OCEAN DC',
    },
    poweroceanfit: {
        identifiers: 'HC31xxxx',
        manufacturer: 'Ecoflow',
        model: 'Power OCEAN DC FIT',
        name: 'Power OCEAN DC FIT',
    },
    poweroceanplus: {
        identifiers: 'R37xxxx',
        manufacturer: 'Ecoflow',
        model: 'Power OCEAN Plus',
        name: 'Power OCEAN Plus',
        spec: {
            capacity: '60kWh',
            mpptInput: '40kW',
            inv: '29,9kW',
        },
    },
    alternator: {
        identifiers: 'F371ZEBxxxx',
        manufacturer: 'Ecoflow',
        model: 'Alternator 800W',
        name: 'Alternator 800W',
    },
    stream_ac_pro: {
        identifiers: 'BK31Zxxx',
        manufacturer: 'Ecoflow',
        model: 'Stream AC, 1920Wh',
        name: 'Stream AC Pro',
        spec: {
            capacity: '1920Wh, 19,2V',
            acInputPower: '1050W charge, 2300W',
            acOutputGrid: '800W',
            acOutput: '1200W',
        },
    },
    stream_pro: {
        identifiers: 'BK11Zxxx',
        manufacturer: 'Ecoflow',
        model: 'Stream Ultra, 1920Wh',
        name: 'Stream AC',
        spec: {
            capacity: '1920Wh, 19,2V',
            acInputPower: '1050W charge, 2300W',
            acOutputGrid: '800W',
            acOutput: '1200W',
            acOutputMax: '2300W',
            solarInput: '3*500W,15-60V, 14A',
        },
    },
    stream_ultra: {
        identifiers: 'BK11Zxxx',
        manufacturer: 'Ecoflow',
        model: 'Stream Ultra, 1920Wh',
        name: 'Stream AC',
        productId: 14338,
        spec: {
            capacity: '1920Wh, 19,2V',
            acInputPower: '1050W charge, 2300W',
            acOutputGrid: '800W',
            acOutput: '1200W',
            acOutputMax: '2300W',
            solarInput: '4*500W,15-60V, 14A',
        },
    },
};

module.exports = {
    models,
};
