/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {};